using  System;
using  System.Collections.Generic;
using  System.Linq.Expressions;
using  System.Web;
using  Umbraco.Core.Models;
using  Umbraco.Core.Models.PublishedContent;
using  Umbraco.Web;
using  Umbraco.ModelsBuilder;
using  Umbraco.ModelsBuilder.Umbraco;
[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "be9fdb9f5f256a0d")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.2")]


// FILE: models.generated.cs

//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------















namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Page</summary>
	[PublishedContentModel("page")]
	public partial class Page : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "page";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Page(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Page, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Trang Chủ</summary>
	[PublishedContentModel("trangChu")]
	public partial class TrangChu : Page
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "trangChu";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TrangChu(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TrangChu, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Tin Tuc</summary>
	[PublishedContentModel("tinTuc")]
	public partial class TinTuc : Page
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "tinTuc";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TinTuc(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TinTuc, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Chi Tiet Tin Tuc</summary>
	[PublishedContentModel("chiTietTinTuc")]
	public partial class ChiTietTinTuc : Page
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "chiTietTinTuc";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ChiTietTinTuc(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ChiTietTinTuc, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Giới Thiệu</summary>
	[PublishedContentModel("gioiThieu")]
	public partial class GioiThieu : Page
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "gioiThieu";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GioiThieu(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GioiThieu, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Đào Tạo</summary>
	[PublishedContentModel("daoTao")]
	public partial class DaoTao : Page
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "daoTao";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DaoTao(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DaoTao, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Tuyển Sinh</summary>
	[PublishedContentModel("tuyenSinh")]
	public partial class TuyenSinh : Page
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "tuyenSinh";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TuyenSinh(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TuyenSinh, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Misc</summary>
	[PublishedContentModel("misc")]
	public partial class Misc : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "misc";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Misc(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Misc, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Tab</summary>
	[PublishedContentModel("tab")]
	public partial class Tab : Misc
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "tab";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Tab(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Tab, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Nội Dung
		///</summary>
		[ImplementPropertyType("noiDung")]
		public IHtmlString NoiDung
		{
			get { return this.GetPropertyValue<IHtmlString>("noiDung"); }
		}
	}

	/// <summary>Giới Thiệu Chung</summary>
	[PublishedContentModel("gioiThieuChung")]
	public partial class GioiThieuChung : GioiThieu
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "gioiThieuChung";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GioiThieuChung(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GioiThieuChung, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Cơ Cấu Tổ Chức</summary>
	[PublishedContentModel("coCauToChuc")]
	public partial class CoCauToChuc : GioiThieu
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "coCauToChuc";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CoCauToChuc(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CoCauToChuc, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Hình Ảnh Tiêu Biểu</summary>
	[PublishedContentModel("hinhAnhTieuBieu")]
	public partial class HinhAnhTieuBieu : GioiThieu
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hinhAnhTieuBieu";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HinhAnhTieuBieu(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HinhAnhTieuBieu, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Ban Giám Đốc</summary>
	[PublishedContentModel("banGiamDoc")]
	public partial class BanGiamDoc : CoCauToChuc
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "banGiamDoc";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BanGiamDoc(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BanGiamDoc, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Ban Giám Đốc Item</summary>
	[PublishedContentModel("banGiamDocItem")]
	public partial class BanGiamDocItem : BanGiamDoc
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "banGiamDocItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BanGiamDocItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BanGiamDocItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Ảnh
		///</summary>
		[ImplementPropertyType("anh")]
		public IPublishedContent Anh
		{
			get { return this.GetPropertyValue<IPublishedContent>("anh"); }
		}

		///<summary>
		/// Cấp Bậc
		///</summary>
		[ImplementPropertyType("capBac")]
		public string CapBac
		{
			get { return this.GetPropertyValue<string>("capBac"); }
		}

		///<summary>
		/// Chức Vụ
		///</summary>
		[ImplementPropertyType("chucVu")]
		public string ChucVu
		{
			get { return this.GetPropertyValue<string>("chucVu"); }
		}

		///<summary>
		/// Danh Hiệu
		///</summary>
		[ImplementPropertyType("danhHieu")]
		public string DanhHieu
		{
			get { return this.GetPropertyValue<string>("danhHieu"); }
		}

		///<summary>
		/// Họ Tên
		///</summary>
		[ImplementPropertyType("hoTen")]
		public string HoTen
		{
			get { return this.GetPropertyValue<string>("hoTen"); }
		}
	}

	/// <summary>Khối Cơ Quan</summary>
	[PublishedContentModel("khoiCoQuan")]
	public partial class KhoiCoQuan : CoCauToChuc
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "khoiCoQuan";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public KhoiCoQuan(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<KhoiCoQuan, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Khối Cơ Quan Item</summary>
	[PublishedContentModel("khoiCoQuanItem")]
	public partial class KhoiCoQuanItem : KhoiCoQuan
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "khoiCoQuanItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public KhoiCoQuanItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<KhoiCoQuanItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Ban Chỉ Huy
		///</summary>
		[ImplementPropertyType("banChiHuy")]
		public string BanChiHuy
		{
			get { return this.GetPropertyValue<string>("banChiHuy"); }
		}

		///<summary>
		/// Chức Năng
		///</summary>
		[ImplementPropertyType("chucNang")]
		public string ChucNang
		{
			get { return this.GetPropertyValue<string>("chucNang"); }
		}

		///<summary>
		/// Nhiệm Vụ
		///</summary>
		[ImplementPropertyType("nhiemVu")]
		public string NhiemVu
		{
			get { return this.GetPropertyValue<string>("nhiemVu"); }
		}

		///<summary>
		/// Thành Tích
		///</summary>
		[ImplementPropertyType("thanhTich")]
		public string ThanhTich
		{
			get { return this.GetPropertyValue<string>("thanhTich"); }
		}
	}

	/// <summary>Khối Khoa Viện</summary>
	[PublishedContentModel("khoiKhoaVien")]
	public partial class KhoiKhoaVien : CoCauToChuc
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "khoiKhoaVien";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public KhoiKhoaVien(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<KhoiKhoaVien, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Khối Khoa Viện Item</summary>
	[PublishedContentModel("khoiKhoaVienItem")]
	public partial class KhoiKhoaVienItem : KhoiKhoaVien
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "khoiKhoaVienItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public KhoiKhoaVienItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<KhoiKhoaVienItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Ban Chỉ Huy
		///</summary>
		[ImplementPropertyType("banChiHuy")]
		public string BanChiHuy
		{
			get { return this.GetPropertyValue<string>("banChiHuy"); }
		}

		///<summary>
		/// Chức Năng
		///</summary>
		[ImplementPropertyType("chucNang")]
		public string ChucNang
		{
			get { return this.GetPropertyValue<string>("chucNang"); }
		}

		///<summary>
		/// Nhiệm Vụ
		///</summary>
		[ImplementPropertyType("nhiemVu")]
		public string NhiemVu
		{
			get { return this.GetPropertyValue<string>("nhiemVu"); }
		}

		///<summary>
		/// Thành Tích
		///</summary>
		[ImplementPropertyType("thanhTich")]
		public string ThanhTich
		{
			get { return this.GetPropertyValue<string>("thanhTich"); }
		}
	}

	/// <summary>Khối Đơn Vị Quản Lý Học Viên</summary>
	[PublishedContentModel("khoiDonViQuanLyHocVien")]
	public partial class KhoiDonViQuanLyHocVien : CoCauToChuc
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "khoiDonViQuanLyHocVien";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public KhoiDonViQuanLyHocVien(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<KhoiDonViQuanLyHocVien, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Khối Đơn Vị Quản Lý Học Viên Item</summary>
	[PublishedContentModel("khoiDonViQuanLyHocVienItem")]
	public partial class KhoiDonViQuanLyHocVienItem : KhoiDonViQuanLyHocVien
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "khoiDonViQuanLyHocVienItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public KhoiDonViQuanLyHocVienItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<KhoiDonViQuanLyHocVienItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ĐT Giới Thiệu Chung</summary>
	[PublishedContentModel("dTGioiThieuChung")]
	public partial class DTgioiThieuChung : DaoTao
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dTGioiThieuChung";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DTgioiThieuChung(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DTgioiThieuChung, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Nội Dung
		///</summary>
		[ImplementPropertyType("noiDung")]
		public IHtmlString NoiDung
		{
			get { return this.GetPropertyValue<IHtmlString>("noiDung"); }
		}
	}

	/// <summary>ĐT Đào Tạo Chuyển Cấp Liên Thông</summary>
	[PublishedContentModel("dTDaoTaoChuyenCapLienThong")]
	public partial class DTdaoTaoChuyenCapLienThong : DaoTao
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dTDaoTaoChuyenCapLienThong";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DTdaoTaoChuyenCapLienThong(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DTdaoTaoChuyenCapLienThong, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ĐT Cam Kết Chuẩn Đầu Ra</summary>
	[PublishedContentModel("dTCamKetChuanDauRa")]
	public partial class DTcamKetChuanDauRa : DaoTao
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dTCamKetChuanDauRa";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DTcamKetChuanDauRa(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DTcamKetChuanDauRa, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ĐT Đào Tạo Đại Học</summary>
	[PublishedContentModel("dTDaoTaoDaiHoc")]
	public partial class DTdaoTaoDaiHoc : DaoTao
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dTDaoTaoDaiHoc";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DTdaoTaoDaiHoc(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DTdaoTaoDaiHoc, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ĐT Đào Tạo Sau Đại Học</summary>
	[PublishedContentModel("dTDaoTaoSauDaiHoc")]
	public partial class DTdaoTaoSauDaiHoc : DaoTao
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dTDaoTaoSauDaiHoc";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DTdaoTaoSauDaiHoc(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DTdaoTaoSauDaiHoc, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ĐT Tra Cứu Điểm Thi</summary>
	[PublishedContentModel("dTTraCuuDiemThi")]
	public partial class DTtraCuuDiemThi : DaoTao
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dTTraCuuDiemThi";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DTtraCuuDiemThi(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DTtraCuuDiemThi, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ĐT Bổ Túc Bồi Dưỡng</summary>
	[PublishedContentModel("dTBoTucBoiDuong")]
	public partial class DTboTucBoiDuong : DaoTao
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dTBoTucBoiDuong";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DTboTucBoiDuong(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DTboTucBoiDuong, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>TS Tuyển Sinh Sau Đại Học</summary>
	[PublishedContentModel("tSTuyenSinhSauDaiHoc")]
	public partial class TStuyenSinhSauDaiHoc : TuyenSinh
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "tSTuyenSinhSauDaiHoc";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TStuyenSinhSauDaiHoc(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TStuyenSinhSauDaiHoc, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>TS Liên Thông Đại Học</summary>
	[PublishedContentModel("tSLienThongDaiHoc")]
	public partial class TSlienThongDaiHoc : TuyenSinh
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "tSLienThongDaiHoc";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TSlienThongDaiHoc(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TSlienThongDaiHoc, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>TS Một Số Câu Hỏi Thường Gặp</summary>
	[PublishedContentModel("tSMotSoCauHoiThuongGap")]
	public partial class TSmotSoCauHoiThuongGap : TuyenSinh
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "tSMotSoCauHoiThuongGap";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TSmotSoCauHoiThuongGap(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TSmotSoCauHoiThuongGap, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>TS Tuyển Sinh Đại Học</summary>
	[PublishedContentModel("tSTuyenSinhDaiHoc")]
	public partial class TStuyenSinhDaiHoc : TuyenSinh
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "tSTuyenSinhDaiHoc";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TStuyenSinhDaiHoc(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TStuyenSinhDaiHoc, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>TS Thông Tin Chung</summary>
	[PublishedContentModel("tSThongTinChung")]
	public partial class TSthongTinChung : TuyenSinh
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "tSThongTinChung";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TSthongTinChung(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TSthongTinChung, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Nghiên Cứu Khoa Học</summary>
	[PublishedContentModel("nghienCuuKhoaHoc")]
	public partial class NghienCuuKhoaHoc : Page
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "nghienCuuKhoaHoc";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NghienCuuKhoaHoc(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NghienCuuKhoaHoc, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>NCKH Các Chương Trình Dự Án Đề Tài</summary>
	[PublishedContentModel("nCKHCacChuongTrinhDuAnDeTai")]
	public partial class NCkhcacChuongTrinhDuAnDeTai : NghienCuuKhoaHoc
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "nCKHCacChuongTrinhDuAnDeTai";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NCkhcacChuongTrinhDuAnDeTai(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NCkhcacChuongTrinhDuAnDeTai, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>NCKH Các Hội Đồng Khoa Học</summary>
	[PublishedContentModel("nCKHCacHoiDongKhoaHoc")]
	public partial class NCkhcacHoiDongKhoaHoc : NghienCuuKhoaHoc
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "nCKHCacHoiDongKhoaHoc";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NCkhcacHoiDongKhoaHoc(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NCkhcacHoiDongKhoaHoc, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>NCKH Các Sản Phẩm Khoa Học</summary>
	[PublishedContentModel("nCKHCacSanPhamKhoaHoc")]
	public partial class NCkhcacSanPhamKhoaHoc : NghienCuuKhoaHoc
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "nCKHCacSanPhamKhoaHoc";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NCkhcacSanPhamKhoaHoc(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NCkhcacSanPhamKhoaHoc, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>NCKH Giới Thiệu Chung</summary>
	[PublishedContentModel("nCKHGioiThieuChung")]
	public partial class NCkhgioiThieuChung : NghienCuuKhoaHoc
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "nCKHGioiThieuChung";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NCkhgioiThieuChung(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NCkhgioiThieuChung, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>NCKH Một Số Thành Tựu</summary>
	[PublishedContentModel("nCKHMotSoThanhTuu")]
	public partial class NCkhmotSoThanhTuu : NghienCuuKhoaHoc
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "nCKHMotSoThanhTuu";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NCkhmotSoThanhTuu(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NCkhmotSoThanhTuu, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Cơ Sở Kỹ Thuật</summary>
	[PublishedContentModel("coSoKyThuat")]
	public partial class CoSoKyThuat : Page
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "coSoKyThuat";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CoSoKyThuat(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CoSoKyThuat, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>CSKT Khai Thác Cơ Sở Kỹ Thuật</summary>
	[PublishedContentModel("cSKTKhaiThacCoSoKyThuat")]
	public partial class CSktkhaiThacCoSoKyThuat : CoSoKyThuat
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "cSKTKhaiThacCoSoKyThuat";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CSktkhaiThacCoSoKyThuat(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CSktkhaiThacCoSoKyThuat, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>CSKT Năng Lực Các Cơ Sở</summary>
	[PublishedContentModel("cSKTNangLucCacCoSo")]
	public partial class CSktnangLucCacCoSo : CoSoKyThuat
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "cSKTNangLucCacCoSo";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CSktnangLucCacCoSo(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CSktnangLucCacCoSo, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Hợp Tác Quốc Tế</summary>
	[PublishedContentModel("hopTacQuocTe")]
	public partial class HopTacQuocTe : Page
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hopTacQuocTe";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HopTacQuocTe(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HopTacQuocTe, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>HTQT Giới Thiệu Chung</summary>
	[PublishedContentModel("hTQTGioiThieuChung")]
	public partial class HTqtgioiThieuChung : HopTacQuocTe
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hTQTGioiThieuChung";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HTqtgioiThieuChung(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HTqtgioiThieuChung, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>HTQT Các Chương Trình Hợp Tác</summary>
	[PublishedContentModel("hTQTCacChuongTrinhHopTac")]
	public partial class HTqtcacChuongTrinhHopTac : HopTacQuocTe
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hTQTCacChuongTrinhHopTac";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HTqtcacChuongTrinhHopTac(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HTqtcacChuongTrinhHopTac, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>HTQT Các Hoạt Động Hợp Tác</summary>
	[PublishedContentModel("hTQTCacHoatDongHopTac")]
	public partial class HTqtcacHoatDongHopTac : HopTacQuocTe
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hTQTCacHoatDongHopTac";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HTqtcacHoatDongHopTac(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HTqtcacHoatDongHopTac, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>HTQT Liên Kết</summary>
	[PublishedContentModel("hTQTLienKet")]
	public partial class HTqtlienKet : HopTacQuocTe
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hTQTLienKet";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HTqtlienKet(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HTqtlienKet, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>HTQT Tiêu Chuẩn Đối Tượng ĐTNN</summary>
	[PublishedContentModel("hTQTTieuChuanDoiTuongDTNN")]
	public partial class HTqttieuChuanDoiTuongDtnn : HopTacQuocTe
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hTQTTieuChuanDoiTuongDTNN";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HTqttieuChuanDoiTuongDtnn(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HTqttieuChuanDoiTuongDtnn, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Thư Viện</summary>
	[PublishedContentModel("thuVien")]
	public partial class ThuVien : Page
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "thuVien";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ThuVien(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ThuVien, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Đảm Bảo Chất Lượng</summary>
	[PublishedContentModel("damBaoChatLuong")]
	public partial class DamBaoChatLuong : Page
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "damBaoChatLuong";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DamBaoChatLuong(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DamBaoChatLuong, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ĐBCL Hệ Thống ĐBCL</summary>
	[PublishedContentModel("dBCLHeThongDBCL")]
	public partial class DBclheThongDbcl : DamBaoChatLuong
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dBCLHeThongDBCL";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DBclheThongDbcl(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DBclheThongDbcl, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ĐBCL Kiểm Định Chất Lượng</summary>
	[PublishedContentModel("dBCLKiemDinhChatLuong")]
	public partial class DBclkiemDinhChatLuong : DamBaoChatLuong
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dBCLKiemDinhChatLuong";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DBclkiemDinhChatLuong(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DBclkiemDinhChatLuong, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ĐBCL Văn Bản Pháp Quy</summary>
	[PublishedContentModel("dBCLVanBanPhapQuy")]
	public partial class DBclvanBanPhapQuy : DamBaoChatLuong
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dBCLVanBanPhapQuy";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DBclvanBanPhapQuy(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DBclvanBanPhapQuy, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ĐBCL Ý Kiến Phản Hồi</summary>
	[PublishedContentModel("dBCLYKienPhanHoi")]
	public partial class DBclykienPhanHoi : DamBaoChatLuong
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dBCLYKienPhanHoi";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DBclykienPhanHoi(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DBclykienPhanHoi, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Học Sinh Sinh Viên</summary>
	[PublishedContentModel("hocSinhSinhVien")]
	public partial class HocSinhSinhVien : Page
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hocSinhSinhVien";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HocSinhSinhVien(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HocSinhSinhVien, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>HSSV Các Văn Bản Biểu Mẫu</summary>
	[PublishedContentModel("hSSVCacVanBanBieuMau")]
	public partial class HSsvcacVanBanBieuMau : HocSinhSinhVien
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hSSVCacVanBanBieuMau";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HSsvcacVanBanBieuMau(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HSsvcacVanBanBieuMau, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>HSSV Hoạt Động NCKH</summary>
	[PublishedContentModel("hSSVHoatDongNCKH")]
	public partial class HSsvhoatDongNckh : HocSinhSinhVien
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hSSVHoatDongNCKH";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HSsvhoatDongNckh(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HSsvhoatDongNckh, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>HSSV Hoạt Động Đoàn Thanh Niên</summary>
	[PublishedContentModel("hSSVHoatDongDoanThanhNien")]
	public partial class HSsvhoatDongDoanThanhNien : HocSinhSinhVien
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hSSVHoatDongDoanThanhNien";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HSsvhoatDongDoanThanhNien(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HSsvhoatDongDoanThanhNien, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>HSSV Học Bổng</summary>
	[PublishedContentModel("hSSVHocBong")]
	public partial class HSsvhocBong : HocSinhSinhVien
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hSSVHocBong";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HSsvhocBong(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HSsvhocBong, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>HSSV Ký Túc Xá</summary>
	[PublishedContentModel("hSSVKyTucXa")]
	public partial class HSsvkyTucXa : HocSinhSinhVien
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hSSVKyTucXa";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HSsvkyTucXa(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HSsvkyTucXa, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Liên Hệ</summary>
	[PublishedContentModel("lienHe")]
	public partial class LienHe : Page
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "lienHe";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public LienHe(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LienHe, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>NCKH Các Nhóm Nghiên Cứu</summary>
	[PublishedContentModel("nCKHCacNhomNghienCuu")]
	public partial class NCkhcacNhomNghienCuu : NghienCuuKhoaHoc
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "nCKHCacNhomNghienCuu";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NCkhcacNhomNghienCuu(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NCkhcacNhomNghienCuu, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>HSSV Giới Thiệu Chung</summary>
	[PublishedContentModel("hSSVGioiThieuChung")]
	public partial class HSsvgioiThieuChung : HocSinhSinhVien
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hSSVGioiThieuChung";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HSsvgioiThieuChung(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HSsvgioiThieuChung, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}



// EOF
